<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN3rdXqO\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN3rdXqO/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerN3rdXqO.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerN3rdXqO\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerN3rdXqO\App_KernelTestDebugContainer([
    'container.build_hash' => 'N3rdXqO',
    'container.build_id' => 'ff6c0865',
    'container.build_time' => 1669237758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN3rdXqO');
