<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_create_movie' => [[], ['_controller' => 'App\\Controller\\CreateMovieController::create'], [], [['text', '/create/movie']], [], [], []],
    'app_hello2_world' => [[], ['_controller' => 'App\\Controller\\Hello2WorldController::index'], [], [['text', '/hello_b']], [], [], []],
    'hello' => [['name'], ['name' => 'nicolas', '_controller' => 'App\\Controller\\Hello2WorldController::afficheNom'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/hello']], [], [], []],
    'app_hello_world' => [[], ['_controller' => 'App\\Controller\\HelloWorldController::index'], [], [['text', '/hello/world']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'app_list_movie' => [[], ['_controller' => 'App\\Controller\\ListMovieController::index'], [], [['text', '/list/movie']], [], [], []],
    'app_load_movies' => [[], ['_controller' => 'App\\Controller\\LoadMoviesController::index'], [], [['text', '/load/movies']], [], [], []],
    'app_show_movie' => [['id'], ['_controller' => 'App\\Controller\\ShowMovieController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/show/movie']], [], [], []],
];
