<?php

namespace ContainerZUfA7Nn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iqyAD4I.App\Entity\Movie' shared service.
     *
     * @return \App\Entity\Movie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iqyAD4I": it references class "App\\Entity\\Movie" but no such service exists.');
    }
}
