<?php

namespace ContainerNwXjYY9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOmdbQueryCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\OmdbQueryCommand' shared autowired service.
     *
     * @return \App\Command\OmdbQueryCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/OmdbQueryCommand.php';

        $container->privates['App\\Command\\OmdbQueryCommand'] = $instance = new \App\Command\OmdbQueryCommand(($container->privates['App\\Omdb\\OmdbGateway'] ?? $container->load('getOmdbGatewayService')), ($container->privates['App\\Repository\\MovieRepository'] ?? $container->load('getMovieRepositoryService')));

        $instance->setName('app:omdb:query');
        $instance->setDescription('Search for a movie in the OMDb Api.');

        return $instance;
    }
}
