<?php

namespace ContainerNwXjYY9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOmdbGatewayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Omdb\OmdbGateway' shared autowired service.
     *
     * @return \App\Omdb\OmdbGateway
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Omdb/OmdbGateway.php';

        return $container->privates['App\\Omdb\\OmdbGateway'] = new \App\Omdb\OmdbGateway(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), $container->getEnv('OMDB_API_KEY'));
    }
}
