<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZUfA7Nn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZUfA7Nn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZUfA7Nn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZUfA7Nn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZUfA7Nn\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZUfA7Nn',
    'container.build_id' => 'bd5e74ab',
    'container.build_time' => 1669382115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZUfA7Nn');
